import { v4 as uuid } from 'uuid';

const ABMlist = [
  {
    id: uuid(),
    img: '/static/images/products/product_1.png',
    nombre: 'Mouse Genius DX-110',
    categoria: 'Mouse',
    marca: 'Genius',
    modelo: 'DX-110',
    interfaz: 'USB',
    peso: 'Aprox. 85g',
    precio: 500,
    stock: 30,
		descripcion: '',
  },
  {
    id: uuid(),
    img: '/static/images/products/product_2.png',
    nombre: 'Mouse Genius DX-125',
    categoria: 'Mouse',
    marca: 'Genius',
    modelo: 'DX-125',
    interfaz: 'USB',
    peso: 'Aprox. 85g',
    precio: 700,
    stock: 20,
		descripcion: '',
  },
  {
    id: uuid(),
    img: '/static/images/products/product_3.png',
    nombre: 'Teclado Genius KB-116',
    categoria: 'Teclado',
    marca: 'Genius',
    modelo: 'KB-116',
    interfaz: 'USB',
    peso: 'Aprox. 488g',
    precio: 350,
    stock: 12,
		descripcion: '',
  },
  {
    id: uuid(),
    img: '/static/images/products/product_4.png',
    nombre: 'Teclado Genius KB-118',
    categoria: 'Teclado',
    marca: 'Genius',
    modelo: 'KB-118',
    interfaz: 'USB',
    peso: 'Aprox. 467g',
    precio: 400,
    stock: 8,
		descripcion: '',
  },
  {
    id: uuid(),
    img: '/static/images/products/product_5.png',
    nombre: 'Parlante Genius SW-21-370',
    categoria: 'Parlante',
    marca: 'Genius',
    modelo: 'SW-21-370',
    interfaz: 'USB',
    peso: 'Aprox. 1500g',
    precio: 700,
    stock: 10,
		descripcion: '',
  },
  {
    id: uuid(),
    img: '/static/images/products/product_6.png',
    nombre: 'Parlante Genius SW-21-375',
    categoria: 'Parlante',
    marca: 'Genius',
    modelo: 'SW-21-375',
    interfaz: 'USB',
    peso: 'Aprox. 1700g',
    precio: 700,
    stock: 10,
		descripcion: '',
  },
  {
    id: uuid(),
    img: '/static/images/products/product_7.png',
    nombre: 'Parlante Genius SP-HF500A',
    categoria: 'Parlante',
    marca: 'Genius',
    modelo: 'SP-HF500A',
    interfaz: 'USB',
    peso: 'Aprox. 2547g',
    precio: 650,
    stock: 8,
		descripcion: '',
  },
  {
    id: uuid(),
    img: '/static/images/products/product_8.png',
    nombre: 'Parlante Genius SP-HF800A',
    categoria: 'Parlante',
    marca: 'Genius',
    modelo: 'SP-HF800A',
    interfaz: 'USB',
    peso: 'Aprox. 2142g',
    precio: 600,
    stock: 10,
		descripcion: '',
  },
];
export default ABMlist;
